# Generated by Django 2.0.5 on 2018-06-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('dob', models.DateField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
