# Generated by Django 2.0.5 on 2018-06-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Fe-Male', 'Fe-male')], max_length=10),
        ),
    ]
